In [3]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score,KFold,GridSearchCV,train_test_split
from sklearn.linear_model import LinearRegression ,Ridge,Lasso

In [4]:
df=pd.read_csv("gurgaon_properties_post_feature_selection_v2.csv").drop(columns=['store room','floor_category','balcony'])

In [5]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servent room,furnishing_type,luxury_category
0,flat,sector 92,0.21,1.0,1,Relatively New,336.0,0,0,Medium
1,flat,sector 59,5.90,4.0,4,Moderately old,5350.0,0,0,Medium
2,flat,sector 1,0.90,3.0,3,Moderately old,1900.0,0,0,Low
3,house,sector 15,10.00,5.0,5,Old Property,4518.0,0,0,Low
4,flat,sector 48,0.72,2.0,2,Relatively New,1165.0,0,0,High

In [6]:
# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

In [7]:
df['agePossession']=df['agePossession'].replace({
    'Relatively New':'new',
        'Moderately old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
                                                })

In [8]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servent room,furnishing_type,luxury_category
0,flat,sector 92,0.21,1.0,1,new,336.0,0,0,Medium
1,flat,sector 59,5.90,4.0,4,old,5350.0,0,0,Medium
2,flat,sector 1,0.90,3.0,3,old,1900.0,0,0,Low
3,house,sector 15,10.00,5.0,5,old,4518.0,0,0,Low
4,flat,sector 48,0.72,2.0,2,new,1165.0,0,0,High

In [9]:
df['property_type']=df['property_type'].replace({'flat':0,'house':1})

C:\Users\sarth\AppData\Local\Temp\ipykernel_24168\3053022205.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type']=df['property_type'].replace({'flat':0,'house':1})

In [10]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servent room,furnishing_type,luxury_category
0,0,sector 92,0.21,1.0,1,new,336.0,0,0,Medium
1,0,sector 59,5.90,4.0,4,old,5350.0,0,0,Medium
2,0,sector 1,0.90,3.0,3,old,1900.0,0,0,Low
3,1,sector 15,10.00,5.0,5,old,4518.0,0,0,Low
4,0,sector 48,0.72,2.0,2,new,1165.0,0,0,High

In [11]:
df['luxury_category']=df['luxury_category'].replace({'Low':0,"Medium":1,"High":2})

C:\Users\sarth\AppData\Local\Temp\ipykernel_24168\1761035597.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category']=df['luxury_category'].replace({'Low':0,"Medium":1,"High":2})

In [12]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servent room,furnishing_type,luxury_category
0,0,sector 92,0.21,1.0,1,new,336.0,0,0,1
1,0,sector 59,5.90,4.0,4,old,5350.0,0,0,1
2,0,sector 1,0.90,3.0,3,old,1900.0,0,0,0
3,1,sector 15,10.00,5.0,5,old,4518.0,0,0,0
4,0,sector 48,0.72,2.0,2,new,1165.0,0,0,2

In [13]:
new_df=pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True)

In [14]:
X=new_df.drop(columns='price')
y=new_df['price']
y_log=np.log1p(y)
X.shape,y_log

((3639, 102),
 0       0.190620
 1       1.931521
 2       0.641854
 3       2.397895
 4       0.542324
           ...
 3634    1.208960
 3635    1.131402
 3636    1.945910
 3637    0.717840
 3638    0.970779
 Name: price, Length: 3639, dtype: float64)

In [15]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [16]:
X_scaled=pd.DataFrame(X_scaled,columns=X.columns)

In [17]:
X_scaled

,property_type,bedRoom,bathroom,built_up_area,servent room,furnishing_type,luxury_category,sector_sector 10,sector_sector 102,sector_sector 103,...,sector_sector 89,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,agePossession_old,agePossession_under construction
0,-0.536788,-1.664363,-1.555934,-1.241375,-0.309442,-0.681065,0.460524,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,5.979764,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249
1,-0.536788,0.722951,0.505740,2.767521,-0.309442,-0.681065,0.460524,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,1.625621,-0.186249
2,-0.536788,-0.072820,-0.181485,0.009106,-0.309442,-0.681065,-0.964516,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,1.625621,-0.186249
3,1.862932,1.518723,1.192964,2.102304,-0.309442,-0.681065,-0.964516,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,1.625621,-0.186249
4,-0.536788,-0.868591,-0.868709,-0.578556,-0.309442,-0.681065,1.885565,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3634,-0.536788,-0.072820,0.505740,0.549596,-0.309442,1.563860,0.460524,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249
3635,-0.536788,-0.868591,-0.868709,-0.674501,-0.309442,-0.681065,-0.964516,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249
3636,-0.536788,-0.072820,0.505740,0.355308,-0.309442,1.563860,-0.964516,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,1.625621,-0.186249
3637,-0.536788,-0.072820,-0.181485,-0.165993,-0.309442,1.563860,0.460524,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249
3638,-0.536788,-0.072820,-0.181485,0.049084,-0.309442,-0.681065,0.460524,-0.05752,-0.175722,-0.108057,...,-0.127266,-0.088057,-0.157422,-0.068509,-0.167231,-0.049793,-0.123879,-0.108057,-0.615150,-0.186249

In [18]:
model=LinearRegression()
k_fold=KFold(n_splits=10,random_state=42, shuffle=True)
score=cross_val_score(model,X_scaled,y_log,cv=k_fold,scoring='r2')

In [19]:
 score.mean(),score.std(),score

(np.float64(0.8346873415604342),
 np.float64(0.024487706466719644),
 array([0.83089491, 0.81117786, 0.82688001, 0.84628788, 0.85414357,
        0.82912905, 0.7783982 , 0.84487925, 0.86298845, 0.86209424]))

In [20]:
# apply lasso and ridge and then do hyperparameter tuning
lasso=Lasso()
lasso_params={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
grid=GridSearchCV(lasso,lasso_params,cv=k_fold,scoring='r2')

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y_log,test_size=0.2,random_state=42)

In [22]:
grid.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]},
             scoring='r2')

In [23]:
grid.best_params_

{'alpha': 0.001}

In [24]:
grid.best_score_

np.float64(0.8340577226386177)

In [25]:
ridge=Ridge()
ridge_params={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
grid=GridSearchCV(ridge,ridge_params,cv=k_fold,scoring='r2')

In [26]:
grid.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]},
             scoring='r2')

In [27]:
grid.best_params_

{'alpha': 1}

In [28]:
grid.best_score_

np.float64(0.8353354494462344)

In [29]:
model=Ridge(alpha=1)
k_fold=KFold(n_splits=10,random_state=42, shuffle=True)
score=cross_val_score(model,X_scaled,y_log,cv=k_fold,scoring='r2')

In [30]:
score.mean(),score.std()

(np.float64(0.8346881421047467), np.float64(0.02445438482255275))

In [31]:
ridge.fit(X_scaled,y_log)

Ridge()

In [32]:
ridge.coef_

array([ 0.07284487,  0.04927071,  0.08943429,  0.21852534,  0.07576352,
        0.01149813,  0.00965537,  0.00973699,  0.06627671,  0.02127553,
        0.03289995,  0.00024211,  0.0279733 ,  0.01346847,  0.04521508,
        0.05482202,  0.00080987,  0.02756281,  0.03449033,  0.04764122,
        0.05822391,  0.00313149, -0.00153374,  0.04265896,  0.00846232,
        0.02367941,  0.03015558, -0.00041963,  0.05251888,  0.0117796 ,
        0.03454188,  0.07279335,  0.08706783,  0.00889699,  0.06129972,
        0.00649643,  0.01202653,  0.03209931,  0.05620789,  0.02004106,
        0.03218003,  0.01833067,  0.0152738 ,  0.00823614,  0.0143345 ,
        0.02415878,  0.0806342 ,  0.03276372,  0.02628055,  0.02464556,
        0.04719074,  0.05214322,  0.00320408,  0.0871518 ,  0.00484964,
        0.01469603,  0.0615159 ,  0.06136377,  0.0211113 ,  0.0315836 ,
        0.03649403,  0.03313713,  0.04364734, -0.00239161,  0.03802002,
        0.06134768,  0.05724681,  0.06136399,  0.10811256,  0.07456375,
        0.06840672,  0.02822488,  0.04763676,  0.01605912,  0.05327741,
        0.01352038,  0.05085483,  0.00472515,  0.03610788,  0.01545632,
        0.02116612,  0.00929532,  0.04395115,  0.0011231 ,  0.00783666,
        0.05222447,  0.03287013,  0.0290427 ,  0.01430676,  0.04597724,
        0.02337989,  0.02531189,  0.03149658,  0.00499402,  0.02049474,
        0.01459103,  0.0077356 ,  0.00662929,  0.00100284,  0.01387215,
        0.01764416,  0.00134696])

In [33]:
ridge=Ridge(alpha=0.01)
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.01)

In [34]:
X.shape

(3639, 102)

In [35]:
coef_df=pd.DataFrame(ridge.coef_.reshape(1,102),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename (columns={'level_1':'feature',0:'coef'})

In [36]:
coef_df

                              feature      coef
0                       property_type  0.072787
1                             bedRoom  0.049238
2                            bathroom  0.089436
3                       built_up_area  0.218648
4                        servent room  0.075755
..                                ...       ...
97                   sector_sector 93  0.007062
98                   sector_sector 95  0.002059
99                   sector_sector 99  0.014796
100                 agePossession_old  0.017830
101  agePossession_under construction  0.001347

[102 rows x 2 columns]

In [88]:
import statsmodels.api as sm 
x_with_const =sm.add_constant(X_scaled)
model=sm.OLS(y_log,x_with_const).fit(-)
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.846
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                     191.0
Date:                Sat, 21 Mar 2026   Prob (F-statistic):               0.00
Time:                        18:54:21   Log-Likelihood:                 360.56
No. Observations:                3639   AIC:                            -515.1
Df Residuals:                    3536   BIC:                             123.4
Df Model:                         102
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                                1.0431      0.004    283.035      0.000       1.036       1.050
property_type                        0.0728      0.006     11.738      0.000       0.061       0.085
bedRoom                              0.0492      0.007      7.276      0.000       0.036       0.063
bathroom                             0.0894      0.007     13.223      0.000       0.076       0.103
built_up_area                        0.2186      0.005     41.403      0.000       0.208       0.229
servent room                         0.0758      0.005     14.175      0.000       0.065       0.086
furnishing_type                      0.0114      0.004      2.711      0.007       0.003       0.020
luxury_category                      0.0096      0.004      2.261      0.024       0.001       0.018
sector_sector 10                     0.0102      0.004      2.407      0.016       0.002       0.019
sector_sector 102                    0.0678      0.007      9.249      0.000       0.053       0.082
sector_sector 103                    0.0222      0.005      4.103      0.000       0.012       0.033
sector_sector 104                    0.0341      0.006      5.384      0.000       0.022       0.047
sector_sector 105                    0.0009      0.005      0.187      0.851      -0.008       0.010
sector_sector 106                    0.0289      0.006      5.233      0.000       0.018       0.040
sector_sector 107                    0.0146      0.006      2.441      0.015       0.003       0.026
sector_sector 108                    0.0463      0.006      7.811      0.000       0.035       0.058
sector_sector 109                    0.0562      0.007      8.285      0.000       0.043       0.069
sector_sector 11                     0.0015      0.005      0.313      0.755      -0.008       0.011
sector_sector 110                    0.0282      0.005      6.127      0.000       0.019       0.037
sector_sector 111                    0.0352      0.005      7.529      0.000       0.026       0.044
sector_sector 112                    0.0483      0.005     10.167      0.000       0.039       0.058
sector_sector 113                    0.0592      0.005     10.835      0.000       0.048       0.070
sector_sector 12                     0.0040      0.005      0.762      0.446      -0.006       0.014
sector_sector 13                    -0.0011      0.004     -0.270      0.787      -0.009       0.007
sector_sector 14                     0.0433      0.005      9.605      0.000       0.034       0.052
sector_sector 15                     0.0088      0.004      2.198      0.028       0.001       0.017
sector_sector 17                     0.0241      0.004      5.767      0.000       0.016       0.032
sector_sector 2                      0.0313      0.006      5.086      0.000       0.019       0.043
sector_sector 21                 -7.798e-05      0.004     -0.020      0.984      -0.008       0.008
sector_sector 22                     0.0532      0.005     11.584      0.000       0.044       0.062
sector_sector 23                     0.0123      0.004      2.830      0.005       0.004       0.021
sector_sector 24                     0.0352      0.005      7.481      0.000       0.026       0.044
sector_sector 25                     0.0737      0.005     13.867      0.000       0.063       0.084
sector_sector 26                     0.0880      0.005     16.037      0.000       0.077       0.099
sector_sector 27                     0.0091      0.004      2.386      0.017       0.002       0.017
sector_sector 28                     0.0622      0.005     11.826      0.000       0.052       0.073
sector_sector 3                      0.0074      0.005      1.352      0.176      -0.003       0.018
sector_sector 30                     0.0123      0.004      3.144      0.002       0.005       0.020
sector_sector 31                     0.0326      0.004      7.808      0.000       0.024       0.041
sector_sector 33                     0.0574      0.006      9.203      0.000       0.045       0.070
sector_sector 36                     0.0207      0.005      4.422      0.000       0.012       0.030
sector_sector 37                     0.0337      0.007      4.526      0.000       0.019       0.048
sector_sector 38                     0.0188      0.004      4.430      0.000       0.010       0.027
sector_sector 39                     0.0157      0.004      3.749      0.000       0.008       0.024
sector_sector 4                      0.0092      0.006      1.609      0.108      -0.002       0.020
sector_sector 40                     0.0147      0.004      3.711      0.000       0.007       0.022
sector_sector 41                     0.0247      0.004      5.747      0.000       0.016       0.033
sector_sector 43                     0.0817      0.006     13.708      0.000       0.070       0.093
sector_sector 45                     0.0332      0.004      8.101      0.000       0.025       0.041
sector_sector 46                     0.0268      0.004      6.262      0.000       0.018       0.035
sector_sector 47                     0.0252      0.004      5.659      0.000       0.016       0.034
sector_sector 48                     0.0493      0.010      5.176      0.000       0.031       0.068
sector_sector 49                     0.0531      0.006      9.591      0.000       0.042       0.064
sector_sector 5                      0.0036      0.004      0.877      0.380      -0.004       0.012
sector_sector 50                     0.0883      0.006     14.522      0.000       0.076       0.100
sector_sector 51                     0.0053      0.004      1.285      0.199      -0.003       0.013
sector_sector 52                     0.0152      0.004      3.530      0.000       0.007       0.024
sector_sector 53                     0.0621      0.004     14.343      0.000       0.054       0.071
sector_sector 54                     0.0621      0.005     12.766      0.000       0.053       0.072
sector_sector 55                     0.0216      0.004      5.155      0.000       0.013       0.030
sector_sector 56                     0.0326      0.006      5.654      0.000       0.021       0.044
sector_sector 57                     0.0372      0.005      7.770      0.000       0.028       0.047
sector_sector 58                     0.0335      0.004      8.320      0.000       0.026       0.041
sector_sector 59                     0.0444      0.005      9.206      0.000       0.035       0.054
sector_sector 6                     -0.0019      0.004     -0.456      0.649      -0.010       0.006
sector_sector 60                     0.0386      0.004      8.748      0.000       0.030       0.047
sector_sector 61                     0.0623      0.005     11.590      0.000       0.052       0.073
sector_sector 62                     0.0578      0.004     13.014      0.000       0.049       0.067
sector_sector 63                     0.0621      0.005     12.578      0.000       0.052       0.072
sector_sector 65                     0.1095      0.007     16.094      0.000       0.096       0.123
sector_sector 66                     0.0755      0.005     13.942      0.000       0.065       0.086
sector_sector 67                     0.0696      0.006     11.151      0.000       0.057       0.082
sector_sector 68                     0.0290      0.005      5.732      0.000       0.019       0.039
sector_sector 69                     0.0490      0.007      7.050      0.000       0.035       0.063
sector_sector 7                      0.0169      0.005      3.143      0.002       0.006       0.028
sector_sector 70                     0.0547      0.007      7.662      0.000       0.041       0.069
sector_sector 71                     0.0143      0.005      2.952      0.003       0.005       0.024
sector_sector 72                     0.0516      0.005     10.451      0.000       0.042       0.061
sector_sector 73                     0.0050      0.004      1.292      0.196      -0.003       0.013
sector_sector 74                     0.0367      0.005      8.108      0.000       0.028       0.046
sector_sector 76                     0.0160      0.004      3.673      0.000       0.007       0.025
sector_sector 77                     0.0219      0.005      4.488      0.000       0.012       0.032
sector_sector 78                     0.0099      0.004      2.243      0.025       0.001       0.018
sector_sector 79                     0.0452      0.006      6.982      0.000       0.033       0.058
sector_sector 8                      0.0015      0.004      0.372      0.710      -0.007       0.010
sector_sector 80                     0.0081      0.004      2.077      0.038       0.000       0.016
sector_sector 81                     0.0536      0.007      7.892      0.000       0.040       0.067
sector_sector 82                     0.0340      0.006      5.675      0.000       0.022       0.046
sector_sector 83                     0.0302      0.006      4.820      0.000       0.018       0.043
sector_sector 84                     0.0153      0.006      2.711      0.007       0.004       0.026
sector_sector 85                     0.0475      0.007      6.511      0.000       0.033       0.062
sector_sector 86                     0.0245      0.006      4.070      0.000       0.013       0.036
sector_sector 88                     0.0260      0.005      5.426      0.000       0.017       0.035
sector_sector 89                     0.0326      0.006      5.501      0.000       0.021       0.044
sector_sector 9                      0.0057      0.005      1.172      0.241      -0.004       0.015
sector_sector 90                     0.0218      0.007      3.236      0.001       0.009       0.035
sector_sector 91                     0.0152      0.004      3.413      0.001       0.006       0.024
sector_sector 92                     0.0091      0.007      1.301      0.193      -0.005       0.023
sector_sector 93                     0.0071      0.004      1.713      0.087      -0.001       0.015
sector_sector 95                     0.0021      0.006      0.353      0.724      -0.009       0.014
sector_sector 99                     0.0148      0.005      2.734      0.006       0.004       0.025
agePossession_old                    0.0178      0.005      3.517      0.000       0.008       0.028
agePossession_under construction     0.0013      0.004      0.349      0.727      -0.006       0.009
==============================================================================
Omnibus:                      485.555   Durbin-Watson:                   2.036
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4960.572
Skew:                          -0.252   Prob(JB):                         0.00
Kurtosis:                       8.698   Cond. No.                         18.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [89]:
y_log.std()

0.5592449060829198

In [90]:
X_scaled['bedRoom'].std()

1.0001374287095028

In [91]:
b=0.049238*(0.5592449060829198/1.0001374287095028)

In [93]:
b=np.expm1(b)

In [94]:
b
# this means on incresing the no of bedroom our price incresed by 0.27 lakh

np.float64(0.02791483364783144)

In [95]:
# do it for built up  area  
X_scaled['built_up_area'].std()

1.000137428709508

In [96]:
0.049238*(0.5592449060829198/1.000137428709508)

0.027532316954921924